services:
   redis:
      image: redis:7-alpine
      restart: always
      env_file: config.env
      ports:
         - "${REDIS_PORT}:${REDIS_PORT}"
      expose:
         - "${REDIS_PORT}"
      volumes:
         - redis-data:${REDIS_DATA}

   postgres:
      image: postgres:16-alpine
      restart: always
      env_file: config.env
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_USERNAME: ${POSTGRES_USERNAME}
         POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
         PGDATA: ${POSTGRES_DATA}
      ports:
         - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      expose:
         - "${POSTGRES_PORT}"
      volumes:
         - postgres-data:${POSTGRES_DATA}

   bot:
      build: .
      restart: always
      env_file: config.env
      depends_on:
         - redis
         - postgres

volumes:
   redis-data:
   postgres-data: